# Удалена устаревшая директива version

services:
  db:
    build: ./db
    restart: always
    volumes:
      - ./db/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: sunsayShop
    ports:
      - '27088:27017'
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://root:password@db:27017/sunsayShop?authSource=admin

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend